config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'todos#index'

  resources :todos, except: :show
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  enum status: { incomplete: 0, complete: 1 }

  validates :title, presence: true

  default_scope -> { in_order_of(:status, %w[incomplete complete]) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

# List, create, update and delete todos with Turbo Rails
class TodosController < ApplicationController
  before_action :set_todo, only: %i[edit update destroy]

  # GET /todos
  def index
    @todos = Todo.all
  end

  # GET /todos/1/edit
  def edit; end

  # POST /todos
  def create
    @todo = Todo.new(todo_params)

    respond_to { |format| create_render(format) }
  end

  # PATCH/PUT /todos/1
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        reload_todos
        format.html { redirect_to todos_url }
      else
        format.turbo_stream { render :form }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to todos_url }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_params
    params.require(:todo).permit(:title, :status)
  end

  def reload_todos
    Turbo::StreamsChannel.broadcast_replace_to(
      'todos',
      target: 'todos',
      partial: 'todos/todos',
      locals: { todos: Todo.all }
    )
  end

  def create_render(format)
    if @todo.save
      @todo = Todo.new
      reload_todos
      format.html { redirect_to todos_url }
    else
      format.html { render :new, status: :unprocessable_entity }
    end
    format.turbo_stream { render :form }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboTodos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, id: "#{dom_id(todo)}_form") do |form| %>
  <% if todo.errors.any? %>
    <% todo.errors.each do |error| %>
      <p class="error"><%= error.full_message %></p>
    <% end %>
  <% end %>

  <div class="todo">
    <%= form.text_field :title, placeholder: "Add a new todo", 'aria-label': 'Title' %>
    <%= form.submit %>
    <%= link_to 'Cancel', Todo, class: 'red button' if todo.id %>
</div>

<% end %>

app/views/todos/_todo.html.erb
<div id="<%= "#{dom_id(todo)}_item" %>">
  <%= turbo_frame_tag dom_id(todo) do %>
    <div class=" <%= 'complete' if todo.complete? %> todo">
      <span class='title'>
         <%= todo.title %>
      </span>

      <% if todo.complete? %>
        <%= button_to "Mark incomplete", todo_path(todo, todo: { status: 'incomplete'}), method: :patch, class: "grey button" %>
      <% else %>
        <%= button_to "Mark complete", todo_path(todo, todo: { status: 'complete'}), method: :patch, class: "green button" %>
      <% end %>

      <%= link_to "Edit", edit_todo_path(todo), class: "button" %>
      <%= button_to "Delete", todo_path(todo), method: :delete, class: "red button" %>
    </div>
  <% end %>
</div>

app/views/todos/_todos.html.erb
<div id="todos">
  <%= render todos %>
</div>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove("#{helpers.dom_id(@todo)}_item") %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag dom_id(@todo) do %>
  <%= render "form", todo: @todo %>
<% end %>

app/views/todos/form.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@todo)}_form" do %>
  <%= render "form", todo: @todo %>
<% end %>

app/views/todos/index.html.erb
<h1>Turbo Todos</h1>

<h2>New todo</h2>
<%= render "form", todo: Todo.new %>

<h2>List of todos</h2>
<%= turbo_stream_from "todos" %>
<%= render partial: "todos", locals: { todos: @todos } %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<%= link_to 'Back to todos', todos_path %>